(load "funcionesAux.lisp")
(defun porcentaje-color ()
    (let* ((rojo (cdr (obtener-color :rojo))) 
           (verde (cdr (obtener-color :verde)))
           (amarillo (cdr (obtener-color :amarillo)))
           (ciclo (+ rojo verde amarillo)))
    
        (list (cons 'rojo (float (* 100 (/ rojo ciclo)))) 
              (cons 'amarillo (float (* 100 (/ amarillo ciclo)))) 
              (cons 'verde (float (* 100 (/ verde ciclo)))))
    )
)
